# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

image: elizabethdev/gitpod:sinope_lithium

jetbrains:
  intellij:
    prebuilds:
      version: both
    plugins:
      - com.github.copilot

tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
